### ISSUE TITLE
[Tracking issue] Proof system prerequisites

### ISSUE THREAD

**Issue by sharnoff** [tc-lang/trenchcoat#8]
This will hopefully serve as a single place to collect the various changes that need to be made before we can start on the proof system. These aren't *strictly* ordered, but where there's a clear chain of requirements, I've tried put them in that order.

- [x] Expand type system (change `Value` to support the unit type `()` and booleans)
  - [x] Require type hints in function parameters (NOTE: Currently missing return types)
  - [x] Add type-checking to 'verify' (or in a separate module) - both on expressions and function arguments
- [x] Implement boolean operators (currently unimplemented in 'exec' [here](https://github.com/tc-lang/trenchcoat/blob/e4cb33b0a896916a188337ce7df07181987637c6/src/exec.rs#L296) and [here](https://github.com/tc-lang/trenchcoat/blob/e4cb33b0a896916a188337ce7df07181987637c6/src/exec.rs#L306))
- [ ] Add support for `if` conditions (with `else`)
